version: '3.8'
services:
  db:
    image: postgres
    restart: always
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=spring_redis
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD-SHELL", "psql -h localhost -U postgres -d spring_redis -c 'SELECT 1;'" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/:delegated